package com.wkq.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wkq.database.dao.ExceptionInfo;
import com.wkq.database.dao.AdTimeInfo;

import com.wkq.database.dao.ExceptionInfoDao;
import com.wkq.database.dao.AdTimeInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig exceptionInfoDaoConfig;
    private final DaoConfig adTimeInfoDaoConfig;

    private final ExceptionInfoDao exceptionInfoDao;
    private final AdTimeInfoDao adTimeInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        exceptionInfoDaoConfig = daoConfigMap.get(ExceptionInfoDao.class).clone();
        exceptionInfoDaoConfig.initIdentityScope(type);

        adTimeInfoDaoConfig = daoConfigMap.get(AdTimeInfoDao.class).clone();
        adTimeInfoDaoConfig.initIdentityScope(type);

        exceptionInfoDao = new ExceptionInfoDao(exceptionInfoDaoConfig, this);
        adTimeInfoDao = new AdTimeInfoDao(adTimeInfoDaoConfig, this);

        registerDao(ExceptionInfo.class, exceptionInfoDao);
        registerDao(AdTimeInfo.class, adTimeInfoDao);
    }
    
    public void clear() {
        exceptionInfoDaoConfig.clearIdentityScope();
        adTimeInfoDaoConfig.clearIdentityScope();
    }

    public ExceptionInfoDao getExceptionInfoDao() {
        return exceptionInfoDao;
    }

    public AdTimeInfoDao getAdTimeInfoDao() {
        return adTimeInfoDao;
    }

}
